/*
 *  JapaneseVocabEditorPanel.java
 *
 *  GNU GPL License.
 */
package psyberchi.app.japanesevocabjsoneditor;

/**
 *
 * @author Kendall Conrad
 */
public class JapaneseVocabEditorPanel extends javax.swing.JPanel {

	/**
	 * Creates new form JapaneseVocabEditorPanel
	 */
	public JapaneseVocabEditorPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField1.setText("english");
        jPanel1.add(jTextField1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("English:");
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextField2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField2.setText("romaji");
        jPanel2.add(jTextField2, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Romaji:");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel2.add(jLabel2, java.awt.BorderLayout.WEST);

        add(jPanel2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTextField3.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 22)); // NOI18N
        jTextField3.setText("かな");
        jPanel5.add(jTextField3, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Kana:");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel5.add(jLabel3, java.awt.BorderLayout.WEST);

        add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jTextField4.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 22)); // NOI18N
        jTextField4.setText("感じ");
        jPanel6.add(jTextField4, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Kanji:");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel6.add(jLabel4, java.awt.BorderLayout.WEST);

        add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Lesson:");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel7.add(jLabel5, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jSpinner1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinner1.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(jSpinner1);

        jPanel7.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
