/*
 *  JapaneseVocabEditor.java
 *
 *  GNU GPL License.
 */
package psyberchi.app.japanesevocabjsoneditor;

import java.util.ArrayList;

/**
 *
 * @author Kendall Conrad
 */
public class JapaneseVocabEditor extends javax.swing.JFrame {

	/**
	 * A container for all of the current set of vocabulary.
	 */
	private ArrayList<VocabItem> vocabulary = new ArrayList<VocabItem>();
	/**
	 * The current category chosen.
	 */
	private String currentCategory;

	/**
	 * Creates new form JapaneseVocabEditor
	 */
	public JapaneseVocabEditor() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar = new javax.swing.JToolBar();
        jButtonToolbarSave = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanelCategories = new javax.swing.JPanel();
        jScrollPaneCategories = new javax.swing.JScrollPane();
        jListCategories = new javax.swing.JList();
        jPanelCategoryButtons = new javax.swing.JPanel();
        jButtonCategoryAdd = new javax.swing.JButton();
        jButtonCategoryDelete = new javax.swing.JButton();
        jPanelRomanji = new javax.swing.JPanel();
        jScrollPaneRomaji = new javax.swing.JScrollPane();
        jListRomaji = new javax.swing.JList();
        jPanelRomajiButtons = new javax.swing.JPanel();
        jButtonRomajiAdd = new javax.swing.JButton();
        jButtonRomajiDelete = new javax.swing.JButton();
        jButtonRomajiMove = new javax.swing.JButton();
        japaneseVocabEditorPanel = new psyberchi.app.japanesevocabjsoneditor.JapaneseVocabEditorPanel();
        jPanelButtons = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jToolBar.setRollover(true);

        jButtonToolbarSave.setText("Save");
        jButtonToolbarSave.setFocusable(false);
        jButtonToolbarSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonToolbarSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButtonToolbarSave);

        getContentPane().add(jToolBar, java.awt.BorderLayout.NORTH);

        jPanelMain.setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(220);
        jSplitPane.setDividerSize(8);
        jSplitPane.setResizeWeight(0.5);

        jPanelCategories.setLayout(new java.awt.BorderLayout());

        jListCategories.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneCategories.setViewportView(jListCategories);

        jPanelCategories.add(jScrollPaneCategories, java.awt.BorderLayout.CENTER);

        jPanelCategoryButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonCategoryAdd.setText("+");
        jButtonCategoryAdd.setIconTextGap(0);
        jButtonCategoryAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanelCategoryButtons.add(jButtonCategoryAdd);

        jButtonCategoryDelete.setText("-");
        jButtonCategoryDelete.setIconTextGap(0);
        jButtonCategoryDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanelCategoryButtons.add(jButtonCategoryDelete);

        jPanelCategories.add(jPanelCategoryButtons, java.awt.BorderLayout.SOUTH);

        jSplitPane.setLeftComponent(jPanelCategories);

        jPanelRomanji.setLayout(new java.awt.BorderLayout());

        jListRomaji.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneRomaji.setViewportView(jListRomaji);

        jPanelRomanji.add(jScrollPaneRomaji, java.awt.BorderLayout.CENTER);

        jPanelRomajiButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jButtonRomajiAdd.setText("+");
        jButtonRomajiAdd.setIconTextGap(0);
        jButtonRomajiAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanelRomajiButtons.add(jButtonRomajiAdd);

        jButtonRomajiDelete.setText("-");
        jButtonRomajiDelete.setIconTextGap(0);
        jButtonRomajiDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanelRomajiButtons.add(jButtonRomajiDelete);

        jButtonRomajiMove.setText("mv");
        jPanelRomajiButtons.add(jButtonRomajiMove);

        jPanelRomanji.add(jPanelRomajiButtons, java.awt.BorderLayout.SOUTH);

        jSplitPane.setRightComponent(jPanelRomanji);

        jPanelMain.add(jSplitPane, java.awt.BorderLayout.CENTER);

        japaneseVocabEditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vocabulary Editor"));
        jPanelMain.add(japaneseVocabEditorPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelButtons, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JapaneseVocabEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JapaneseVocabEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JapaneseVocabEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JapaneseVocabEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new JapaneseVocabEditor().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCategoryAdd;
    private javax.swing.JButton jButtonCategoryDelete;
    private javax.swing.JButton jButtonRomajiAdd;
    private javax.swing.JButton jButtonRomajiDelete;
    private javax.swing.JButton jButtonRomajiMove;
    private javax.swing.JButton jButtonToolbarSave;
    private javax.swing.JList jListCategories;
    private javax.swing.JList jListRomaji;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCategories;
    private javax.swing.JPanel jPanelCategoryButtons;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelRomajiButtons;
    private javax.swing.JPanel jPanelRomanji;
    private javax.swing.JScrollPane jScrollPaneCategories;
    private javax.swing.JScrollPane jScrollPaneRomaji;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JToolBar jToolBar;
    private psyberchi.app.japanesevocabjsoneditor.JapaneseVocabEditorPanel japaneseVocabEditorPanel;
    // End of variables declaration//GEN-END:variables
}
