/*
 *  JapaneseVocabEditorPanel.java
 *
 *  GNU GPL License.
 */
package psyberchi.app.japanesevocabjsoneditor;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Kendall Conrad
 */
public class JapaneseVocabEditorPanel extends javax.swing.JPanel {

	public static final String PROP_MODIFIED = "MODIFIED";
	private VocabItem vocabItem = null;

	/**
	 * Creates new form JapaneseVocabEditorPanel
	 */
	public JapaneseVocabEditorPanel() {
		initComponents();
	}

	public void clearPanel() {
		jTextFieldEnglish.setText("");
		jTextFieldRomaji.setText("");
		jTextFieldKana.setText("");
		jTextFieldKanji.setText("");
		jSpinnerLesson.setValue(0);
	}

	public VocabItem getVocabItem() {
		return vocabItem;
	}

	public boolean setVocabItem(VocabItem item) {
		if (item == null) {
			return false;
		}
		vocabItem = item;
		jTextFieldEnglish.setText(item.getEnglish());
		jTextFieldRomaji.setText(item.getRomanji());
		jTextFieldKana.setText(item.getKana());
		jTextFieldKanji.setText(item.getKanji());
		jSpinnerLesson.getModel().setValue(item.getLesson());
		return true;
	}

	@Override
	public void setEnabled(boolean enable) {
		jTextFieldEnglish.setEnabled(enable);
		jTextFieldRomaji.setEnabled(enable);
		jTextFieldKana.setEnabled(enable);
		jTextFieldKanji.setEnabled(enable);
		jSpinnerLesson.setEnabled(enable);
	}

	public void setEnglish(String str) {
		vocabItem.setEnglish(str);
		jTextFieldEnglish.setText(str);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEnglish = new javax.swing.JPanel();
        jTextFieldEnglish = new javax.swing.JTextField();
        jLabelEnglish = new javax.swing.JLabel();
        jPanelRomaji = new javax.swing.JPanel();
        jTextFieldRomaji = new javax.swing.JTextField();
        jLabelRomaji = new javax.swing.JLabel();
        jPanelKana = new javax.swing.JPanel();
        jTextFieldKana = new javax.swing.JTextField();
        jLabelKana = new javax.swing.JLabel();
        jPanelKanji = new javax.swing.JPanel();
        jTextFieldKanji = new javax.swing.JTextField();
        jLabelKanji = new javax.swing.JLabel();
        jPanelLesson = new javax.swing.JPanel();
        jLabelLesson = new javax.swing.JLabel();
        jPanelLessonSpinner = new javax.swing.JPanel();
        jSpinnerLesson = new javax.swing.JSpinner();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelEnglish.setLayout(new java.awt.BorderLayout());

        jTextFieldEnglish.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldEnglish.setText("english");
        jTextFieldEnglish.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnglishFocusLost(evt);
            }
        });
        jPanelEnglish.add(jTextFieldEnglish, java.awt.BorderLayout.CENTER);

        jLabelEnglish.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelEnglish.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEnglish.setText("English:");
        jLabelEnglish.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelEnglish.add(jLabelEnglish, java.awt.BorderLayout.WEST);

        add(jPanelEnglish);

        jPanelRomaji.setLayout(new java.awt.BorderLayout());

        jTextFieldRomaji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextFieldRomaji.setText("romaji");
        jTextFieldRomaji.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRomajiFocusLost(evt);
            }
        });
        jPanelRomaji.add(jTextFieldRomaji, java.awt.BorderLayout.CENTER);

        jLabelRomaji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelRomaji.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRomaji.setText("Romaji:");
        jLabelRomaji.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelRomaji.add(jLabelRomaji, java.awt.BorderLayout.WEST);

        add(jPanelRomaji);

        jPanelKana.setLayout(new java.awt.BorderLayout());

        jTextFieldKana.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 22)); // NOI18N
        jTextFieldKana.setText("かな");
        jTextFieldKana.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldKanaFocusLost(evt);
            }
        });
        jPanelKana.add(jTextFieldKana, java.awt.BorderLayout.CENTER);

        jLabelKana.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelKana.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelKana.setText("Kana:");
        jLabelKana.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelKana.add(jLabelKana, java.awt.BorderLayout.WEST);

        add(jPanelKana);

        jPanelKanji.setLayout(new java.awt.BorderLayout());

        jTextFieldKanji.setFont(new java.awt.Font("Hiragino Mincho Pro", 0, 22)); // NOI18N
        jTextFieldKanji.setText("感じ");
        jTextFieldKanji.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldKanjiFocusLost(evt);
            }
        });
        jPanelKanji.add(jTextFieldKanji, java.awt.BorderLayout.CENTER);

        jLabelKanji.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelKanji.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelKanji.setText("Kanji:");
        jLabelKanji.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelKanji.add(jLabelKanji, java.awt.BorderLayout.WEST);

        add(jPanelKanji);

        jPanelLesson.setLayout(new java.awt.BorderLayout());

        jLabelLesson.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelLesson.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelLesson.setText("Lesson:");
        jLabelLesson.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanelLesson.add(jLabelLesson, java.awt.BorderLayout.WEST);

        jPanelLessonSpinner.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jSpinnerLesson.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSpinnerLesson.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinnerLesson.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerLessonStateChanged(evt);
            }
        });
        jPanelLessonSpinner.add(jSpinnerLesson);

        jPanelLesson.add(jPanelLessonSpinner, java.awt.BorderLayout.CENTER);

        add(jPanelLesson);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEnglishFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnglishFocusLost
        String oldValue = vocabItem.getEnglish();
        String newValue = jTextFieldEnglish.getText();
		if (!oldValue.equals(newValue)) {
			vocabItem.setEnglish(newValue);
			firePropertyChange(PROP_MODIFIED, oldValue, newValue);
		}
    }//GEN-LAST:event_jTextFieldEnglishFocusLost

    private void jTextFieldRomajiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRomajiFocusLost
        vocabItem.setRomanji(jTextFieldRomaji.getText());
    }//GEN-LAST:event_jTextFieldRomajiFocusLost

    private void jTextFieldKanaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldKanaFocusLost
        vocabItem.setKana(jTextFieldKana.getText());
    }//GEN-LAST:event_jTextFieldKanaFocusLost

    private void jTextFieldKanjiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldKanjiFocusLost
        vocabItem.setKanji(jTextFieldKanji.getText());
    }//GEN-LAST:event_jTextFieldKanjiFocusLost

    private void jSpinnerLessonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerLessonStateChanged
        int val = ((SpinnerNumberModel) jSpinnerLesson.getModel()).getNumber().intValue();
		vocabItem.setLesson(val);
    }//GEN-LAST:event_jSpinnerLessonStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEnglish;
    private javax.swing.JLabel jLabelKana;
    private javax.swing.JLabel jLabelKanji;
    private javax.swing.JLabel jLabelLesson;
    private javax.swing.JLabel jLabelRomaji;
    private javax.swing.JPanel jPanelEnglish;
    private javax.swing.JPanel jPanelKana;
    private javax.swing.JPanel jPanelKanji;
    private javax.swing.JPanel jPanelLesson;
    private javax.swing.JPanel jPanelLessonSpinner;
    private javax.swing.JPanel jPanelRomaji;
    private javax.swing.JSpinner jSpinnerLesson;
    private javax.swing.JTextField jTextFieldEnglish;
    private javax.swing.JTextField jTextFieldKana;
    private javax.swing.JTextField jTextFieldKanji;
    private javax.swing.JTextField jTextFieldRomaji;
    // End of variables declaration//GEN-END:variables
}
