/*
 *  PrefPanel.java
 *
 *  GNU GPL License.
 */
package psyberchi.app.japanesevocabjsoneditor.ui;

import psyberchi.app.japanesevocabjsoneditor.controller.ChangeablePreferences;

/**
 *
 * @author Kendall Conrad
 */
public abstract class PrefPanel extends javax.swing.JPanel implements ChangeablePreferences {
	/**
	 * Creates new form PrefPanel
	 */
	public PrefPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
